# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
 # name = "CV"
  #url = "#CV"
  #weight = 10

#[[main]]
 # name = "Posts"
  #url = "#posts"
  #weight = 20

[[main]]
 # name = "Projects"
#  url = "#projects"
 # weight = 30

#[[main]]
 # name = "Courses"
 # url = "courses/"
  #weight = 50

#[[main]]
 #name = "Contact"
  #url = "mailto:clynncrosby@gmail.com"
 #weight = 60
 
 [[main]]
    name = "LinkedIn"  # A name for the link.
    url = "https://www.linkedin.com/in/courtney-crosby/"  # URL of the section.
    weight = 30  # Position of the link in the menu.

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
    name = "CV"
    url = "files/CV.pdf"
    weight = 10 
    
    [[main]]
    name = "Resume"
    url = "files/Resume.pdf"
    weight = 20 
    
   [[main]]
 name = "Texas Sex Education Testimony"  # A name for the link.
   url = "https://youtu.be/ScTUg8hiRJE"  # URL of the section.
  weight = 30  # Position of the link in the menu.


